<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cadrastro de pessoas</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <header class="bg-red-800 p-6 flex items-center justify-between">
        <div class = "text-white font-bold text-3xl"> Pessoas </div>
        <div>
            <ul class="list-none n-0 p-0 flex items-baseline">
               <li class="n-l-6 "><a href="/ " class="text-red-300 text-2x1 hover:text-white"> todas as pessoas</a> </li>
                <li class="n-l-6 "><a href="/nova-pessoa " class="text-red-300 text-2x1 hover:text-white"> nova pessoas</a> </li>
                <li class="n-l-6 "><a href="/mostar-pessoa " class="text-red-300 text-2x1 hover:text-white"> Mostrar as pessoas</a> </li>
            </ul>


        </div>

    </header>

</body>
</html>